replicaCount: 1
persistence:
  size: 5Gi
service:
  nodePort: 31571
cleanup:
  threshold: 4Gi # This should be around 80% of the total size, this is for the auto cleanup job
ingress:
  enabled: true
  host: registry.unbind.cloud
  authSecret: registry-basic-auth
  annotations: {}