apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkit-config
  namespace: {{ .Release.Namespace }}
data:
  buildkitd.toml: |
    [worker.oci]
    # Limit concurrency of build steps:
    max-parallelism = {{ .Values.maxParallelism }}
    
    {{- /* Process registry entries */}}
    {{- if .Values.registries }}
    {{- range .Values.registries }}
    [registry."{{ .url }}"]
    http = {{ .http | default true }}
    insecure = {{ .insecure | default true }}
    {{- if .ca }}
    ca = ["{{ .ca }}"]
    {{- end }}
    {{- end }}
    {{- end }}
    
    [frontend."dockerfile.v0"]
    enabled = true