# Global settings
global:
  namespace: "unbind-system"

# ServiceAccount
serviceAccount:
  create: true
  name: unbind-api-sa
  annotations: {}

# RBAC
rbac:
  create: true

# Builder configuration
builder:
  rbac:
    create: true
    clusterRoleName: "app-crd-creator"
    clusterRoleBindingName: "app-crd-creator-binding"
  serviceAccount:
    create: true
    name: "builder-serviceaccount"
    annotations: {}

# Database configuration
database:
  host: "pg-unbind"
  port: 5432
  database: "unbind"
  existingSecret: "unbind-db-credentials"
  userKey: "username"
  passwordKey: "password"

# Ingress common configuration
ingress:
  className: "nginx"
  host: "unbind.example.com"
  tls:
    enabled: true
    secretName: "unbind-app-tls"

# UI Configuration
ui:
  enabled: true
  name: unbind-ui
  image:
    repository: "unbindapp/unbind-ui"
    tag: "latest"
    pullPolicy: "Always"
  replicaCount: 2
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  containerPort: 3000
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: true  # Enable this for separate ingress
    annotations:
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
      nginx.ingress.kubernetes.io/proxy-buffering: "off"
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
      nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
      nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
      nginx.ingress.kubernetes.io/session-cookie-name: unbind-session
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/upstream-hash-by: $realip_remote_addr
  env:
    - name: AUTH_SECRET
      valueFrom:
        secretKeyRef:
          name: unbind-authjs-secrets
          key: auth-secret
    - name: AUTH_URL
      value: "https://unbind.example.com/api-internal/auth"
    - name: DEX_CLIENT_ID
      value: "unbind-api"
    - name: DEX_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: dex-client-secrets
          key: unbind-api-secret
    - name: DEX_ISSUER
      value: "https://dex.example.com"
    - name: UNBIND_API_EXTERNAL_URL
      value: "https://unbind.example.com/api"
    - name: UNBIND_API_INTERNAL_URL
      value: "http://unbind-api.unbind-system.svc.cluster.local:8089"
    - name: SITE_URL
      value: "https://unbind.example.com"
  startupProbe:
    enabled: true
    failureThreshold: 30
    periodSeconds: 10
  livenessProbe:
    enabled: true
    initialDelaySeconds: 15
    failureThreshold:  10
    periodSeconds: 10
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    failureThreshold:  20
    periodSeconds: 5

# API Configuration
api:
  enabled: true
  name: unbind-api
  image:
    repository: "unbindapp/unbind-api"
    tag: "latest"
    pullPolicy: "Always"
  replicaCount: 2
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  containerPort: 8089
  service:
    type: ClusterIP
    port: 8089
  ingress:
    enabled: true  # Enable this for separate ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/eventsource: "true"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/websocket-services: unbind-api
  command: ["/app/api"]
  env:
    - name: SYSTEM_NAMESPACE
      value: "unbind-system"
    - name: EXTERNAL_UI_URL
      value: "https://unbind.example.com"
    - name: EXTERNAL_API_URL
      value: "https://unbind.example.com/api"
    - name: EXTERNAL_OAUTH2_URL
      value: "https://unbind.example.com/api/oauth2"
    - name: BOOTSTRAP_WILDCARD_BASE_URL
      value: "https://example.com"
    - name: POSTGRES_HOST
      value: "pg-unbind"
    - name: POSTGRES_PORT
      value: "5432"
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: unbind.pg-unbind.credentials.postgresql.acid.zalan.do
          key: username
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: unbind.pg-unbind.credentials.postgresql.acid.zalan.do
          key: password
    - name: POSTGRES_DB
      value: "unbind"
    - name: REDIS_URL
      value: redis-headless.unbind-system:6379
    - name: DEX_ISSUER_URL
      value: "https://dex.example.com"
    - name: DEX_ISSUER_URL_EXTERNAL
      value: "https://dex.example.com"
    - name: DEX_CLIENT_ID
      value: "unbind-api"
    - name: DEX_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: dex-client-secrets
          key: unbind-api-secret
    - name: KUBE_PROXY_URL
      value: "https://kube-oidc-proxy.unbind-system.svc.cluster.local:443"
    - name: BUILD_IMAGER
      value: unbindapp/unbind-builder:latest
    - name: BUILDER_NAMESPACE
      value: unbind-system
    - name: BOOTSTRAP_CONTAINER_REGISTRY_HOST
      value: docker-registry.unbind-system:5000
    - name: BOOTSTRAP_CONTAINER_REGISTRY_USER
      valueFrom:
        secretKeyRef:
          name: registry-credentials
          key: username
    - name: BOOTSTRAP_CONTAINER_REGISTRY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: registry-credentials
          key: password
    - name: BUILDKIT_HOST
      value: tcp://buildkit.unbind-system:1234
    - name: LOKI_ENDPOINT
      value: http://loki-gateway.unbind-system.svc.cluster.local
    - name: PROMETHEUS_ENDPOINT
      value: http://kube-prometheus-stack-prometheus.unbind-system:9090
  startupProbe:
    enabled: true
    failureThreshold: 30
    periodSeconds: 10
  livenessProbe:
    enabled: true
    initialDelaySeconds: 15
    failureThreshold:  10
    periodSeconds: 10
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    failureThreshold:  20
    periodSeconds: 3

# Auth Configuration
auth:
  enabled: true
  name: unbind-auth
  image:
    repository: "unbindapp/unbind-auth"
    tag: "latest"
    pullPolicy: "Always"
  replicaCount: 2
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  containerPort: 8090
  service:
    type: ClusterIP
    port: 8090
  ingress:
    enabled: true  # Enable this for separate ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
  command: ["/app/oauth2server"]
  env:
    - name: EXTERNAL_UI_URL
      value: "https://unbind.example.com"
    - name: SYSTEM_NAMESPACE
      value: "unbind-system"
    - name: EXTERNAL_OAUTH2_URL
      value: "https://unbind.example.com/api/oauth2"
    - name: POSTGRES_HOST
      value: "pg-unbind"
    - name: POSTGRES_PORT
      value: "5432"
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: unbind.pg-unbind.credentials.postgresql.acid.zalan.do
          key: username
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: unbind.pg-unbind.credentials.postgresql.acid.zalan.do
          key: password
    - name: DEX_ISSUER_URL
      value: "https://dex.example.com"
    - name: DEX_ISSUER_URL_EXTERNAL
      value: "https://dex.example.com"
    - name: DEX_CLIENT_ID
      value: "unbind-api"
    - name: DEX_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: dex-client-secrets
          key: unbind-api-secret
    - name: DEX_CONNECTOR_SECRET
      valueFrom:
        secretKeyRef:
          name: dex-client-secrets
          key: connector-oidc-secret
    - name: REDIS_URL
      value: redis-headless.unbind-system:6379
  startupProbe:
    enabled: true
    failureThreshold: 30
    periodSeconds: 10
  livenessProbe:
    enabled: true
    initialDelaySeconds: 15
    failureThreshold:  10
    periodSeconds: 10
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    failureThreshold:  20
    periodSeconds: 5