# environments/default.yaml
# Default environment settings

global:
  baseDomain: example.com
  namespace: unbind-system

components:
  longhorn:
    enabled: false
  kubePrometheusStack:
    enabled: true
  buildkitd:
    enabled: true
  postgresOperator:
    enabled: true
  database:
    enabled: true

overrides:
  longhorn:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
      reclaimPolicy: Delete
    defaultSettings:
      defaultReplicaCount: 1
  kubePrometheusStack:
    # Configurable retention period
    retention: "7d"
    # Configurable storage size
    storage: "5Gi"
  buildkitd:
    image: moby/buildkit:v0.20.2-rootless
    replicas: 1
    maxParallism: 2
  postgresOperator:
    spiloImage: unbindapp/spilo:17
  database:
    replicaCount: 1
    storage: "5Gi"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 512m
        memory: 1Gi
