{{- if .Values.auth.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.auth.name }}-deployment
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.auth.name }}
    {{- include "unbind.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.auth.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ .Values.auth.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.auth.name }}
        {{- include "unbind.auth.selectorLabels" . | nindent 8 }}
    spec:
      priorityClassName: unbind-high-priority
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for database at $POSTGRES_HOST:$POSTGRES_PORT..."
              until nc -z $POSTGRES_HOST $POSTGRES_PORT; do
                echo "Database not ready, waiting..."
                sleep 2
              done
              echo "Database is ready!"
          env:
            - name: POSTGRES_HOST
              value: {{ .Values | get "overrides.unbind.auth.database.host" (printf "pg-unbind.%s" .Values.global.namespace) }}
            - name: POSTGRES_PORT
              value: {{ .Values | get "overrides.unbind.auth.database.port" "5432" | quote }}
      containers:
        - name: {{ .Values.auth.name }}
          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          {{- if .Values.auth.command }}
          command: {{ .Values.auth.command }}
          {{- end }}
          resources:
            {{- toYaml .Values.auth.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.auth.containerPort }}
          {{- if .Values.auth.env }}
          env:
            {{- toYaml .Values.auth.env | nindent 12 }}
          {{- end }}
          {{- if .Values.auth.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.auth.startupProbe.path }}
              port: {{ .Values.auth.containerPort }}
            failureThreshold: {{ .Values.auth.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.auth.startupProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.auth.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.auth.livenessProbe.path }}
              port: {{ .Values.auth.containerPort }}
            initialDelaySeconds: {{ .Values.auth.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.auth.livenessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.auth.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.auth.readinessProbe.path }}
              port: {{ .Values.auth.containerPort }}
            initialDelaySeconds: {{ .Values.auth.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.auth.readinessProbe.periodSeconds }}
          {{- end }}
{{- end }}