{{- if .Values.combinedIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unbind-combined-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "unbind.labels" . | nindent 4 }}
  annotations:
    {{- if not .Values.combinedIngress.annotations }}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    {{- with .Values.combinedIngress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/eventsource: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/websocket-services: "unbind-api" 
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
spec:
  {{- if .Values.combinedIngress.tls.enabled }}
  ingressClassName: {{ .Values.combinedIngress.className }}
  tls:
    - hosts:
        - {{ .Values.combinedIngress.host }}
      secretName: {{ .Values.combinedIngress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.combinedIngress.host }}
      http:
        paths:
           # 1) /api -> direct to the API service, stripping /api
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.api.name }}
                port:
                  number: {{ .Values.api.service.port }}

          # 2) /oauth2/api -> direct to the Auth service, stripping /oauth2/api
          - path: /oauth2/api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.auth.name }}
                port:
                  number: {{ .Values.auth.service.port }}

          # 3) Everything else -> UI service
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.ui.name }}
                port:
                  number: {{ .Values.ui.service.port }}
{{- end }}