{{- if .Values.combinedIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unbind-combined-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "unbind.labels" . | nindent 4 }}
  {{- with .Values.combinedIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.combinedIngress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.combinedIngress.host }}
      secretName: {{ .Values.combinedIngress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.combinedIngress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ui.name }}
                port:
                  number: {{ .Values.ui.service.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.api.name }}
                port:
                  number: {{ .Values.api.service.port }}
          - path: /oauth2/api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.auth.name }}
                port:
                  number: {{ .Values.auth.service.port }}
{{- end }}