{{- if .Values.builder.rbac.create }}
# ClusterRole for the builder to manage Unbind app services
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.builder.rbac.clusterRoleName }}
  labels:
    {{- include "unbind.labels" . | nindent 4 }}
rules:
  - apiGroups: ["unbind.unbind.app"]
    resources: ["services"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
# ClusterRoleBinding to bind the ServiceAccount to the ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.builder.rbac.clusterRoleBindingName }}
  labels:
    {{- include "unbind.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.builder.serviceAccount.name }}
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.builder.rbac.clusterRoleName }}
  apiGroup: rbac.authorization.k8s.io
{{- if .Values.builder.serviceAccount.create }}
---
# ServiceAccount for the builder
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.builder.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "unbind.labels" . | nindent 4 }}
  {{- with .Values.builder.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}