apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: {{ .Release.Namespace }}
  labels:
    app: registry
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      securityContext:
        fsGroup: 0
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
          env:
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: /var/lib/registry
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
          securityContext:
            runAsUser: 0
      volumes:
        - name: registry-storage
          persistentVolumeClaim:
            claimName: registry-pvc