apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-cleanup-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: registry-cleanup-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "create"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: registry-cleanup-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: registry-cleanup-sa
  namespace: unbind-system
roleRef:
  kind: Role
  name: registry-cleanup-role
  apiGroup: rbac.authorization.k8s.io
