kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "pg-unbind"
  namespace: {{ .Release.Namespace }}
  labels:
    unbind-is-system-db: "true"
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}

spec:
  env:
  - name: ALLOW_NOSSL
    value: "true"

  teamId: "acid"
  postgresql:
    version: "17"
    parameters:
      wal_level: replica
  numberOfInstances: {{ .Values.replicaCount }}
  volume:
    size: {{ .Values.storage }}


  allowedSourceRanges:
    - 0.0.0.0/0

  databases:
    dex: dex
    unbind: unbind

  users:
    dex:
      - LOGIN
    unbind:
      - SUPERUSER

  resources:
    requests:
      cpu: {{ .Values.resources.requests.cpu  }}
      memory: {{ .Values.resources.requests.memory  }}
    limits:
      cpu: {{ .Values.resources.limits.cpu  }}
      memory: {{ .Values.resources.limits.memory  }}