apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-oidc-proxy.fullname" . }}-config
  labels:
    {{- include "kube-oidc-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  oidc.issuer-url: {{ .Values.oidc.issuerUrl }}
  oidc.client-id: {{ .Values.oidc.clientId }}
  oidc.username-claim: {{ .Values.oidc.usernameClaim }}